services:
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/_static
    ports:
      - 80:80
  web:
    build: .
    command: gunicorn mysite.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
      - static_volume:/usr/src/app/_static
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
volumes:
  static_volume: